// export const applications = [
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Stripe",
//     dateApplied: new Date("2025-10-01"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "Microsoft",
//     dateApplied: new Date("2025-10-05"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Full Stack Developer",
//     company: "Notion",
//     dateApplied: new Date("2025-10-08"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Developer",
//     company: "Vercel",
//     dateApplied: new Date("2025-10-11"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer",
//     company: "Shopify",
//     dateApplied: new Date("2025-10-14"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Web Engineer",
//     company: "Linear",
//     dateApplied: new Date("2025-10-18"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Airbnb",
//     dateApplied: new Date("2025-10-20"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "Dropbox",
//     dateApplied: new Date("2025-10-22"),
//     status: "apply",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Developer",
//     company: "Figma",
//     dateApplied: new Date("2025-10-25"),
//     status: "apply",
//   },

//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer",
//     company: "Google",
//     dateApplied: new Date("2025-09-28"),
//     status: "progress",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Netflix",
//     dateApplied: new Date("2025-09-30"),
//     status: "progress",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Developer",
//     company: "Datadog",
//     dateApplied: new Date("2025-10-02"),
//     status: "progress",
//   },

//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer",
//     company: "Amazon",
//     dateApplied: new Date("2025-08-01"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Developer",
//     company: "Apple",
//     dateApplied: new Date("2025-08-04"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "Meta",
//     dateApplied: new Date("2025-08-06"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Full Stack Engineer",
//     company: "Square",
//     dateApplied: new Date("2025-08-09"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Robinhood",
//     dateApplied: new Date("2025-08-11"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Developer",
//     company: "Slack",
//     dateApplied: new Date("2025-08-13"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Web Developer",
//     company: "Discord",
//     dateApplied: new Date("2025-08-16"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer",
//     company: "Atlassian",
//     dateApplied: new Date("2025-08-19"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Developer",
//     company: "HubSpot",
//     dateApplied: new Date("2025-08-22"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "Adobe",
//     dateApplied: new Date("2025-08-25"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Full Stack Developer",
//     company: "Asana",
//     dateApplied: new Date("2025-08-27"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Pinterest",
//     dateApplied: new Date("2025-08-30"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer",
//     company: "Lyft",
//     dateApplied: new Date("2025-09-02"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Web Developer",
//     company: "Twilio",
//     dateApplied: new Date("2025-09-04"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "Reddit",
//     dateApplied: new Date("2025-09-07"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Frontend Engineer",
//     company: "Snap",
//     dateApplied: new Date("2025-09-09"),
//     status: "reject",
//   },
//   {
//     id: crypto.randomUUID(),
//     role: "Software Developer",
//     company: "Palantir",
//     dateApplied: new Date("2025-09-12"),
//     status: "reject",
//   },

//   {
//     id: crypto.randomUUID(),
//     role: "Software Engineer I",
//     company: "OpenAI",
//     dateApplied: new Date("2025-11-01"),
//     status: "offer",
//   },
// ];
